export const father = [
    {
        text: "The same way a loving father feels toward his children—that’s but a sample of your tender feelings toward us, your beloved children, who live in awe of you.",
        verse: "Pslam 103:13",
        category: 'Father',
        version: "TPT",
    },
    {
        text: "See what great love the Father has lavished on us, that we should be called children of God! And that is what we are! The reason the world does not know us is that it did not know him.",
        verse: "1 John 3:1",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "For the Father’s discipline comes only from his passionate love and pleasure for you. Even when it seems like his correction is harsh, it’s still better than any father on earth gives to his child.",
        verse: "Proverbs 3:12",
        category: 'Father',
        version: "TPT",
    },
    {
        text: "But when you pray, go into your room, close the door and pray to your Father, who is unseen. Then your Father, who sees what is done in secret, will reward you.",
        verse: "Matthew 6:6",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "“Look at all the birds—do you think they worry about their existence? They don’t plant or reap or store up food, yet your heavenly Father provides them each with food. Aren’t you much more valuable to your Father than they? So, which one of you by worrying could add anything to your life?",
        verse: "Matthew 6:26-27",
        category: 'Father',
        version: "TPT",
    },
    {
        text: "Father, I want those you have given me to be with me where I am, and to see my glory, the glory you have given me because you loved me before the creation of the world.",
        verse: "John 17:24",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "I give them eternal life, and they shall never perish; no one will snatch them out of my hand. My Father, who has given them to me, is greater than all; no one can snatch them out of my Father’s hand. I and the Father are one.",
        verse: "John 10:28-30",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "So don’t ever be afraid, dearest friends! Your loving Father joyously gives you his kingdom realm with all its promises!",
        verse: "Luke 12:32",
        category: 'Father',
        version: "TPT",
    },
    {
        text: "But to all who did receive him, who believed in his name, he gave the right to become children of God.",
        verse: "John 1:12",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "Be merciful, even as your Father is merciful.",
        verse: "Luke 6:36",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "And whenever you stand praying, forgive, if you have anything against anyone, so that your Father also who is in heaven may forgive you your trespasses.",
        verse: "Mark 11:25",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "No one who denies the Son has the Father. Whoever confesses the Son has the Father also.",
        verse: "1 John 2:23",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "And so that we would know for sure that we are his true children, God released the Spirit of Sonship into our hearts—moving us to cry out intimately, “My Father! You’re our true Father!”",
        verse: "Galatians 4:6",
        category: 'Father',
        version: "TPT",
    },
    {
        text: "Jesus said to her, “Do not cling to me, for I have not yet ascended to the Father; but go to my brothers and say to them, ‘I am ascending to my Father and your Father, to my God and your God.’”",
        verse: "John 20:17",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "Let what you heard from the beginning abide in you. If what you heard from the beginning abides in you, then you too will abide in the Son and in the Father.",
        verse: "1 John 2:24",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "Jesus said to them again, “Peace be with you. As the Father has sent me, even so I am sending you.",
        verse: "John 20:21",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "But when you give to the needy, do not let your left hand know what your right hand is doing, so that your giving may be in secret. And your Father who sees in secret will reward you.",
        verse: "Matthew 6:3-4",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "Yet for us there is one God, the Father, from whom are all things and for whom we exist, and one Lord, Jesus Christ, through whom are all things and through whom we exist.",
        verse: "1 Corinthians 8:6",
        category: 'Father',
        version: "NIV",
    },
    {
        text: "Don’t set the affections of your heart on this world or in loving the things of the world. The love of the Father and the love of the world are incompatible.",
        verse: "1 John 2:15",
        category: 'Father',
        version: "TPT",
    },
]