require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.0'

target 'HolyWhisper' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  target 'HolyWhisperTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  #use_flipper!({ 'Flipper-Folly' => '2.5.3' })
  # use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'HolyWhisper-tvOS' do
  # Pods for HolyWhisper-tvOS

  target 'HolyWhisper-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'BoringSSL-GRPC'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
        end
      end
      # Fix gRPC template keyword warning treated as error in Xcode 26+
      if target.name.start_with?('gRPC') || target.name == 'abseil'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -Wno-missing-template-arg-list-after-template-kw'
        end
      end
      # Fix boost std::unary_function removed in C++17 (Xcode 26+)
      if target.name == 'boost'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -D_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION'
        end
      end
    end
  end